import smtplib
import datetime as dt
import random

# -----------------------------Print Random Quote-----------------------
def random_quote():
    global mondays_quote
    with open('quotes.txt', 'r') as file:
        lines = file.read().splitlines()
        mondays_quote = random.choice(lines)
        return mondays_quote

# -----------------------------------------------------------------------

# ----------------------------Send The Email ----------------------------
def send_email(quote):
    my_email = "rhyder.sharpe@gmail.com"
    # my_other_email = "rhyder.sharpe@yahoo.com"
    password = "desqcbrcqnjkrxwc"  # App Password generated by Google

    with smtplib.SMTP("smtp.gmail.com") as connection_gmail:
        # connection_yahoo = smtplib.SMTP("smtp.mail.yahoo.com")
        connection_gmail.starttls()  # Secure connection
        connection_gmail.login(user=my_email, password=password)
        connection_gmail.sendmail(
            from_addr=my_email,
            to_addrs="rhyder.sharpe@yahoo.com",
            msg=f"Subject:Hello\n\n {quote}"
        )
# -----------------------------------------------------------------------
now = dt.datetime.now()
day_of_week = now.weekday()

if day_of_week == 5:
    random_quote()
    print(mondays_quote)
    send_email(mondays_quote) # Passed into "def send_email(quote):" as quote.
else:
    print("Not the correct day")



# year = now.year
# month = now.month
# day = now.day
# hour = now.hour
# day_of_week = now.weekday()
# print(day_of_week)

# date_of_birth = dt.datetime(year=1990, month=5, day=5, hour=11, minute=11)
# print(date_of_birth)

# connection_gmail.close()
